#! /bin/bash/groovy

pipline{
  agent{
    docker{
      image 'maven:3-alpine'
      label 'my-defined-label'
      args '-v /tmp:/tmp'
    }
  }

  if test 1=2
    then
      echo "abcd"
    else
      echo "edfg"
  fi


}

for loop in 1,2,3,4,5
do
  echo "the values is ${loop}"
done

echo `expr 2+3`